apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels: 
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: yuy910616/front_end
        ports:
        - containerPort: 5000
      nodeSelector:
        cloud.google.com/gke-nodepool: "default-pool"

---
apiVersion: v1
kind: Service
metadata:
  name: flask-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30733
  selector:
    app: frontend
 