apiVersion : v1
kind : PersistentVolume
metadata:
  name: mongodb-pv
  labels: 
    volume: mongo
spec:
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  gcePersistentDisk: 
    pdName: mongodb
    fsType: ext4
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      volume: mongo
  storageClassName: ""
---
kind: ReplicaSet
apiVersion: apps/v1
metadata: 
  name: mongodb
  labels: 
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - image: mongo
        name: mongodb
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        ports:
        - containerPort: 27017
          protocol: TCP
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "1"
      volumes:
        - name: mongodb-data
          persistentVolumeClaim: 
            claimName: mongodb-pvc
      nodeSelector:
        cloud.google.com/gke-nodepool: "default-pool"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
spec: 
  ports:
  - port: 27017
    protocol: TCP
  selector: 
    app: mongodb


